version: '3'

services:
    mysql:
        image: mysql:5.7
        container_name: mysql.${MYSQL_NAME}.docker
        restart: unless-stopped
        environment:
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
            MYSQL_DATABASE: ${MYSQL_NAME}
            MYSQL_USER: ${MYSQL_USER}
            MYSQL_PASSWORD: ${MYSQL_PASSWORD}
        volumes:
            - ~/data/${MYSQL_NAME}.docker:/var/lib/mysql
        ports:
            - ${MYSQL_PORT}:3306
        networks:
            - global

    redis:
        image: redis:latest
        container_name: redis.${MYSQL_NAME}.docker
        networks:
            - global
        ports:
            - ${REDIS_PORT}:6379
        command:
            - 'bash'
            - '-c'
            - 'docker-entrypoint.sh --requirepass "$$REDIS_PASSWORD"'
        environment:
            REDIS_PASSWORD: ${REDIS_PASSWORD}

networks:
    global:
        external: true
